/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.parser;

import postfix.lexer.*;
import postfix.node.*;
import postfix.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList<Object> nodeList;

    private final Lexer lexer;
    private final ListIterator<Object> stack = new LinkedList<Object>().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    @SuppressWarnings({"unchecked","unused"})
    private void push(int numstate, ArrayList<Object> listNode) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            // int middle = (low + high) / 2;
            int middle = (low + high) >>> 1;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList<Object> pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList<Object> list = new ArrayList<Object>();
		        list.add(this.lexer.next());
                        push(this.action[1], list);
                    }
		    break;
                case REDUCE:
                    {
                        int reduction = this.action[1];
                        if(reduction < 500) reduce_0(reduction);
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PProgramme node1 = (PProgramme) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }

    private void reduce_0(int reduction) throws IOException, LexerException, ParserException
    {
        switch(reduction)
        {
            case 0: /* reduce AProgramme$Listedecvar1Programme */
            {
                ArrayList<Object> list = new0();
                push(goTo(0), list);
            }
            break;
            case 1: /* reduce AProgramme$Epsilon1Programme */
            {
                ArrayList<Object> list = new1();
                push(goTo(0), list);
            }
            break;
            case 2: /* reduce AOuExp */
            {
                ArrayList<Object> list = new2();
                push(goTo(1), list);
            }
            break;
            case 3: /* reduce AExp1Exp */
            {
                ArrayList<Object> list = new3();
                push(goTo(1), list);
            }
            break;
            case 4: /* reduce AEtExp1 */
            {
                ArrayList<Object> list = new4();
                push(goTo(2), list);
            }
            break;
            case 5: /* reduce AExp2Exp1 */
            {
                ArrayList<Object> list = new5();
                push(goTo(2), list);
            }
            break;
            case 6: /* reduce AEqualExp2 */
            {
                ArrayList<Object> list = new6();
                push(goTo(3), list);
            }
            break;
            case 7: /* reduce AInfExp2 */
            {
                ArrayList<Object> list = new7();
                push(goTo(3), list);
            }
            break;
            case 8: /* reduce AExp3Exp2 */
            {
                ArrayList<Object> list = new8();
                push(goTo(3), list);
            }
            break;
            case 9: /* reduce APlusExp3 */
            {
                ArrayList<Object> list = new9();
                push(goTo(4), list);
            }
            break;
            case 10: /* reduce ASubExp3 */
            {
                ArrayList<Object> list = new10();
                push(goTo(4), list);
            }
            break;
            case 11: /* reduce AExp4Exp3 */
            {
                ArrayList<Object> list = new11();
                push(goTo(4), list);
            }
            break;
            case 12: /* reduce AMultExp4 */
            {
                ArrayList<Object> list = new12();
                push(goTo(5), list);
            }
            break;
            case 13: /* reduce ADivExp4 */
            {
                ArrayList<Object> list = new13();
                push(goTo(5), list);
            }
            break;
            case 14: /* reduce AExp5Exp4 */
            {
                ArrayList<Object> list = new14();
                push(goTo(5), list);
            }
            break;
            case 15: /* reduce ANonExp5 */
            {
                ArrayList<Object> list = new15();
                push(goTo(6), list);
            }
            break;
            case 16: /* reduce AExp6Exp5 */
            {
                ArrayList<Object> list = new16();
                push(goTo(6), list);
            }
            break;
            case 17: /* reduce AParenteseExp6 */
            {
                ArrayList<Object> list = new17();
                push(goTo(7), list);
            }
            break;
            case 18: /* reduce ANumberExp6 */
            {
                ArrayList<Object> list = new18();
                push(goTo(7), list);
            }
            break;
            case 19: /* reduce AVraiExp6 */
            {
                ArrayList<Object> list = new19();
                push(goTo(7), list);
            }
            break;
            case 20: /* reduce AFauxExp6 */
            {
                ArrayList<Object> list = new20();
                push(goTo(7), list);
            }
            break;
            case 21: /* reduce AVariableExp6 */
            {
                ArrayList<Object> list = new21();
                push(goTo(7), list);
            }
            break;
            case 22: /* reduce AAppelfoncExp6 */
            {
                ArrayList<Object> list = new22();
                push(goTo(7), list);
            }
            break;
            case 23: /* reduce ALireExp6 */
            {
                ArrayList<Object> list = new23();
                push(goTo(7), list);
            }
            break;
            case 24: /* reduce AAppelfonctionAppelfonc */
            {
                ArrayList<Object> list = new24();
                push(goTo(8), list);
            }
            break;
            case 25: /* reduce AAfectationInstr */
            {
                ArrayList<Object> list = new25();
                push(goTo(9), list);
            }
            break;
            case 26: /* reduce ATantqueInstr */
            {
                ArrayList<Object> list = new26();
                push(goTo(9), list);
            }
            break;
            case 27: /* reduce AFonctionInstr */
            {
                ArrayList<Object> list = new27();
                push(goTo(9), list);
            }
            break;
            case 28: /* reduce ASiInstr */
            {
                ArrayList<Object> list = new28();
                push(goTo(9), list);
            }
            break;
            case 29: /* reduce ASinonInstr */
            {
                ArrayList<Object> list = new29();
                push(goTo(9), list);
            }
            break;
            case 30: /* reduce ARetourInstr */
            {
                ArrayList<Object> list = new30();
                push(goTo(9), list);
            }
            break;
            case 31: /* reduce AEcrireInstr */
            {
                ArrayList<Object> list = new31();
                push(goTo(9), list);
            }
            break;
            case 32: /* reduce AListedinstrInstrbloc */
            {
                ArrayList<Object> list = new32();
                push(goTo(10), list);
            }
            break;
            case 33: /* reduce AListdeinstrListeinstr */
            {
                ArrayList<Object> list = new33();
                push(goTo(11), list);
            }
            break;
            case 34: /* reduce AEpsilonListeinstr */
            {
                ArrayList<Object> list = new34();
                push(goTo(11), list);
            }
            break;
            case 35: /* reduce AListedeexpressionListeexp */
            {
                ArrayList<Object> list = new35();
                push(goTo(12), list);
            }
            break;
            case 36: /* reduce AEpsilonListeexp */
            {
                ArrayList<Object> list = new36();
                push(goTo(12), list);
            }
            break;
            case 37: /* reduce ARestelistedeexpressionListeexpbis */
            {
                ArrayList<Object> list = new37();
                push(goTo(13), list);
            }
            break;
            case 38: /* reduce AEpsilonListeexpbis */
            {
                ArrayList<Object> list = new38();
                push(goTo(13), list);
            }
            break;
            case 39: /* reduce AIdentifVar */
            {
                ArrayList<Object> list = new39();
                push(goTo(14), list);
            }
            break;
            case 40: /* reduce AVarindexeeVar */
            {
                ArrayList<Object> list = new40();
                push(goTo(14), list);
            }
            break;
            case 41: /* reduce ADeclarationvarDecvar */
            {
                ArrayList<Object> list = new41();
                push(goTo(15), list);
            }
            break;
            case 42: /* reduce ADeclarationvarindexeeDecvar */
            {
                ArrayList<Object> list = new42();
                push(goTo(15), list);
            }
            break;
            case 43: /* reduce AEntierType */
            {
                ArrayList<Object> list = new43();
                push(goTo(16), list);
            }
            break;
            case 44: /* reduce ABoolType */
            {
                ArrayList<Object> list = new44();
                push(goTo(16), list);
            }
            break;
            case 45: /* reduce ADeclarationfonction$Listedecvar1$Listedecvar2$Type1Decfonc */
            {
                ArrayList<Object> list = new45();
                push(goTo(17), list);
            }
            break;
            case 46: /* reduce ADeclarationfonction$Listedecvar1$Listedecvar2$Epsilon1Decfonc */
            {
                ArrayList<Object> list = new46();
                push(goTo(17), list);
            }
            break;
            case 47: /* reduce ADeclarationfonction$Listedecvar1$Epsilon2$Type1Decfonc */
            {
                ArrayList<Object> list = new47();
                push(goTo(17), list);
            }
            break;
            case 48: /* reduce ADeclarationfonction$Listedecvar1$Epsilon2$Epsilon1Decfonc */
            {
                ArrayList<Object> list = new48();
                push(goTo(17), list);
            }
            break;
            case 49: /* reduce ADeclarationfonction$Epsilon1$Listedecvar2$Type1Decfonc */
            {
                ArrayList<Object> list = new49();
                push(goTo(17), list);
            }
            break;
            case 50: /* reduce ADeclarationfonction$Epsilon1$Listedecvar2$Epsilon1Decfonc */
            {
                ArrayList<Object> list = new50();
                push(goTo(17), list);
            }
            break;
            case 51: /* reduce ADeclarationfonction$Epsilon1$Epsilon2$Type1Decfonc */
            {
                ArrayList<Object> list = new51();
                push(goTo(17), list);
            }
            break;
            case 52: /* reduce ADeclarationfonction$Epsilon1$Epsilon2$Epsilon1Decfonc */
            {
                ArrayList<Object> list = new52();
                push(goTo(17), list);
            }
            break;
            case 53: /* reduce AApreslistedecvarListedecvarbis */
            {
                ArrayList<Object> list = new53();
                push(goTo(18), list);
            }
            break;
            case 54: /* reduce AEpsilonListedecvarbis */
            {
                ArrayList<Object> list = new54();
                push(goTo(18), list);
            }
            break;
            case 55: /* reduce AListedecfoncListedecfonc */
            {
                ArrayList<Object> list = new55();
                push(goTo(19), list);
            }
            break;
            case 56: /* reduce AEpsilonListedecfonc */
            {
                ArrayList<Object> list = new56();
                push(goTo(19), list);
            }
            break;
        }
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new0() /* reduce AProgramme$Listedecvar1Programme */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PProgramme pprogrammeNode1;
        {
            // Block
        PListedecvar plistedecvarNode2;
        PListedecfonc plistedecfoncNode5;
        {
            // Block
        PDecvar pdecvarNode3;
        PListedecvarbis plistedecvarbisNode4;
        pdecvarNode3 = (PDecvar)nodeArrayList1.get(0);
        plistedecvarbisNode4 = (PListedecvarbis)nodeArrayList2.get(0);

        plistedecvarNode2 = new AListedecvarListedecvar(pdecvarNode3, plistedecvarbisNode4);
        }
        plistedecfoncNode5 = (PListedecfonc)nodeArrayList3.get(0);

        pprogrammeNode1 = new AProgrammeProgramme(plistedecvarNode2, plistedecfoncNode5);
        }
	nodeList.add(pprogrammeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new1() /* reduce AProgramme$Epsilon1Programme */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PProgramme pprogrammeNode1;
        {
            // Block
        PListedecvar plistedecvarNode2;
        PListedecfonc plistedecfoncNode3;
        {
            // Block

        plistedecvarNode2 = new AEpsilonListedecvar();
        }
        plistedecfoncNode3 = (PListedecfonc)nodeArrayList1.get(0);

        pprogrammeNode1 = new AProgrammeProgramme(plistedecvarNode2, plistedecfoncNode3);
        }
	nodeList.add(pprogrammeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new2() /* reduce AOuExp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp pexpNode2;
        TOu touNode3;
        PExp1 pexp1Node4;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        touNode3 = (TOu)nodeArrayList2.get(0);
        pexp1Node4 = (PExp1)nodeArrayList3.get(0);

        pexpNode1 = new AOuExp(pexpNode2, touNode3, pexp1Node4);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new3() /* reduce AExp1Exp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PExp1 pexp1Node2;
        pexp1Node2 = (PExp1)nodeArrayList1.get(0);

        pexpNode1 = new AExp1Exp(pexp1Node2);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new4() /* reduce AEtExp1 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp1 pexp1Node1;
        {
            // Block
        PExp1 pexp1Node2;
        TEt tetNode3;
        PExp2 pexp2Node4;
        pexp1Node2 = (PExp1)nodeArrayList1.get(0);
        tetNode3 = (TEt)nodeArrayList2.get(0);
        pexp2Node4 = (PExp2)nodeArrayList3.get(0);

        pexp1Node1 = new AEtExp1(pexp1Node2, tetNode3, pexp2Node4);
        }
	nodeList.add(pexp1Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new5() /* reduce AExp2Exp1 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp1 pexp1Node1;
        {
            // Block
        PExp2 pexp2Node2;
        pexp2Node2 = (PExp2)nodeArrayList1.get(0);

        pexp1Node1 = new AExp2Exp1(pexp2Node2);
        }
	nodeList.add(pexp1Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new6() /* reduce AEqualExp2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp2 pexp2Node1;
        {
            // Block
        PExp2 pexp2Node2;
        TEqual tequalNode3;
        PExp3 pexp3Node4;
        pexp2Node2 = (PExp2)nodeArrayList1.get(0);
        tequalNode3 = (TEqual)nodeArrayList2.get(0);
        pexp3Node4 = (PExp3)nodeArrayList3.get(0);

        pexp2Node1 = new AEqualExp2(pexp2Node2, tequalNode3, pexp3Node4);
        }
	nodeList.add(pexp2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new7() /* reduce AInfExp2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp2 pexp2Node1;
        {
            // Block
        PExp2 pexp2Node2;
        TLess tlessNode3;
        PExp3 pexp3Node4;
        pexp2Node2 = (PExp2)nodeArrayList1.get(0);
        tlessNode3 = (TLess)nodeArrayList2.get(0);
        pexp3Node4 = (PExp3)nodeArrayList3.get(0);

        pexp2Node1 = new AInfExp2(pexp2Node2, tlessNode3, pexp3Node4);
        }
	nodeList.add(pexp2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new8() /* reduce AExp3Exp2 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp2 pexp2Node1;
        {
            // Block
        PExp3 pexp3Node2;
        pexp3Node2 = (PExp3)nodeArrayList1.get(0);

        pexp2Node1 = new AExp3Exp2(pexp3Node2);
        }
	nodeList.add(pexp2Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new9() /* reduce APlusExp3 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp3 pexp3Node1;
        {
            // Block
        PExp3 pexp3Node2;
        TPlus tplusNode3;
        PExp4 pexp4Node4;
        pexp3Node2 = (PExp3)nodeArrayList1.get(0);
        tplusNode3 = (TPlus)nodeArrayList2.get(0);
        pexp4Node4 = (PExp4)nodeArrayList3.get(0);

        pexp3Node1 = new APlusExp3(pexp3Node2, tplusNode3, pexp4Node4);
        }
	nodeList.add(pexp3Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new10() /* reduce ASubExp3 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp3 pexp3Node1;
        {
            // Block
        PExp3 pexp3Node2;
        TMinus tminusNode3;
        PExp4 pexp4Node4;
        pexp3Node2 = (PExp3)nodeArrayList1.get(0);
        tminusNode3 = (TMinus)nodeArrayList2.get(0);
        pexp4Node4 = (PExp4)nodeArrayList3.get(0);

        pexp3Node1 = new ASubExp3(pexp3Node2, tminusNode3, pexp4Node4);
        }
	nodeList.add(pexp3Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new11() /* reduce AExp4Exp3 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp3 pexp3Node1;
        {
            // Block
        PExp4 pexp4Node2;
        pexp4Node2 = (PExp4)nodeArrayList1.get(0);

        pexp3Node1 = new AExp4Exp3(pexp4Node2);
        }
	nodeList.add(pexp3Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new12() /* reduce AMultExp4 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp4 pexp4Node1;
        {
            // Block
        PExp4 pexp4Node2;
        TMult tmultNode3;
        PExp5 pexp5Node4;
        pexp4Node2 = (PExp4)nodeArrayList1.get(0);
        tmultNode3 = (TMult)nodeArrayList2.get(0);
        pexp5Node4 = (PExp5)nodeArrayList3.get(0);

        pexp4Node1 = new AMultExp4(pexp4Node2, tmultNode3, pexp5Node4);
        }
	nodeList.add(pexp4Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new13() /* reduce ADivExp4 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp4 pexp4Node1;
        {
            // Block
        PExp4 pexp4Node2;
        TDiv tdivNode3;
        PExp5 pexp5Node4;
        pexp4Node2 = (PExp4)nodeArrayList1.get(0);
        tdivNode3 = (TDiv)nodeArrayList2.get(0);
        pexp5Node4 = (PExp5)nodeArrayList3.get(0);

        pexp4Node1 = new ADivExp4(pexp4Node2, tdivNode3, pexp5Node4);
        }
	nodeList.add(pexp4Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new14() /* reduce AExp5Exp4 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp4 pexp4Node1;
        {
            // Block
        PExp5 pexp5Node2;
        pexp5Node2 = (PExp5)nodeArrayList1.get(0);

        pexp4Node1 = new AExp5Exp4(pexp5Node2);
        }
	nodeList.add(pexp4Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new15() /* reduce ANonExp5 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp5 pexp5Node1;
        {
            // Block
        TNon tnonNode2;
        PExp5 pexp5Node3;
        tnonNode2 = (TNon)nodeArrayList1.get(0);
        pexp5Node3 = (PExp5)nodeArrayList2.get(0);

        pexp5Node1 = new ANonExp5(tnonNode2, pexp5Node3);
        }
	nodeList.add(pexp5Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new16() /* reduce AExp6Exp5 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp5 pexp5Node1;
        {
            // Block
        PExp6 pexp6Node2;
        pexp6Node2 = (PExp6)nodeArrayList1.get(0);

        pexp5Node1 = new AExp6Exp5(pexp6Node2);
        }
	nodeList.add(pexp5Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new17() /* reduce AParenteseExp6 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp6 pexp6Node1;
        {
            // Block
        TLPar tlparNode2;
        PExp pexpNode3;
        TRPar trparNode4;
        tlparNode2 = (TLPar)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        trparNode4 = (TRPar)nodeArrayList3.get(0);

        pexp6Node1 = new AParenteseExp6(tlparNode2, pexpNode3, trparNode4);
        }
	nodeList.add(pexp6Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new18() /* reduce ANumberExp6 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp6 pexp6Node1;
        {
            // Block
        TNumber tnumberNode2;
        tnumberNode2 = (TNumber)nodeArrayList1.get(0);

        pexp6Node1 = new ANumberExp6(tnumberNode2);
        }
	nodeList.add(pexp6Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new19() /* reduce AVraiExp6 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp6 pexp6Node1;
        {
            // Block
        TVrai tvraiNode2;
        tvraiNode2 = (TVrai)nodeArrayList1.get(0);

        pexp6Node1 = new AVraiExp6(tvraiNode2);
        }
	nodeList.add(pexp6Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new20() /* reduce AFauxExp6 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp6 pexp6Node1;
        {
            // Block
        TFaux tfauxNode2;
        tfauxNode2 = (TFaux)nodeArrayList1.get(0);

        pexp6Node1 = new AFauxExp6(tfauxNode2);
        }
	nodeList.add(pexp6Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new21() /* reduce AVariableExp6 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp6 pexp6Node1;
        {
            // Block
        PVar pvarNode2;
        pvarNode2 = (PVar)nodeArrayList1.get(0);

        pexp6Node1 = new AVariableExp6(pvarNode2);
        }
	nodeList.add(pexp6Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new22() /* reduce AAppelfoncExp6 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp6 pexp6Node1;
        {
            // Block
        PAppelfonc pappelfoncNode2;
        pappelfoncNode2 = (PAppelfonc)nodeArrayList1.get(0);

        pexp6Node1 = new AAppelfoncExp6(pappelfoncNode2);
        }
	nodeList.add(pexp6Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new23() /* reduce ALireExp6 */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExp6 pexp6Node1;
        {
            // Block
        TLire tlireNode2;
        TLPar tlparNode3;
        TRPar trparNode4;
        tlireNode2 = (TLire)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        trparNode4 = (TRPar)nodeArrayList3.get(0);

        pexp6Node1 = new ALireExp6(tlireNode2, tlparNode3, trparNode4);
        }
	nodeList.add(pexp6Node1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new24() /* reduce AAppelfonctionAppelfonc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PAppelfonc pappelfoncNode1;
        {
            // Block
        TIdentif tidentifNode2;
        TLPar tlparNode3;
        PListeexp plisteexpNode4;
        TRPar trparNode5;
        tidentifNode2 = (TIdentif)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        plisteexpNode4 = (PListeexp)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);

        pappelfoncNode1 = new AAppelfonctionAppelfonc(tidentifNode2, tlparNode3, plisteexpNode4, trparNode5);
        }
	nodeList.add(pappelfoncNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new25() /* reduce AAfectationInstr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInstr pinstrNode1;
        {
            // Block
        PVar pvarNode2;
        TEqual tequalNode3;
        PExp pexpNode4;
        TPointVirgule tpointvirguleNode5;
        pvarNode2 = (PVar)nodeArrayList1.get(0);
        tequalNode3 = (TEqual)nodeArrayList2.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);
        tpointvirguleNode5 = (TPointVirgule)nodeArrayList4.get(0);

        pinstrNode1 = new AAfectationInstr(pvarNode2, tequalNode3, pexpNode4, tpointvirguleNode5);
        }
	nodeList.add(pinstrNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new26() /* reduce ATantqueInstr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInstr pinstrNode1;
        {
            // Block
        TTantque ttantqueNode2;
        PExp pexpNode3;
        TFaire tfaireNode4;
        PInstrbloc pinstrblocNode5;
        ttantqueNode2 = (TTantque)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        tfaireNode4 = (TFaire)nodeArrayList3.get(0);
        pinstrblocNode5 = (PInstrbloc)nodeArrayList4.get(0);

        pinstrNode1 = new ATantqueInstr(ttantqueNode2, pexpNode3, tfaireNode4, pinstrblocNode5);
        }
	nodeList.add(pinstrNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new27() /* reduce AFonctionInstr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInstr pinstrNode1;
        {
            // Block
        TIdentif tidentifNode2;
        TLPar tlparNode3;
        PListeexp plisteexpNode4;
        TRPar trparNode5;
        TPointVirgule tpointvirguleNode6;
        tidentifNode2 = (TIdentif)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        plisteexpNode4 = (PListeexp)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tpointvirguleNode6 = (TPointVirgule)nodeArrayList5.get(0);

        pinstrNode1 = new AFonctionInstr(tidentifNode2, tlparNode3, plisteexpNode4, trparNode5, tpointvirguleNode6);
        }
	nodeList.add(pinstrNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new28() /* reduce ASiInstr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInstr pinstrNode1;
        {
            // Block
        TSi tsiNode2;
        PExp pexpNode3;
        TAlors talorsNode4;
        PInstrbloc pinstrblocNode5;
        tsiNode2 = (TSi)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        talorsNode4 = (TAlors)nodeArrayList3.get(0);
        pinstrblocNode5 = (PInstrbloc)nodeArrayList4.get(0);

        pinstrNode1 = new ASiInstr(tsiNode2, pexpNode3, talorsNode4, pinstrblocNode5);
        }
	nodeList.add(pinstrNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new29() /* reduce ASinonInstr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInstr pinstrNode1;
        {
            // Block
        TSi tsiNode2;
        PExp pexpNode3;
        TAlors talorsNode4;
        PInstrbloc pinstrblocNode5;
        TSinon tsinonNode6;
        PInstrbloc pinstrblocNode7;
        tsiNode2 = (TSi)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        talorsNode4 = (TAlors)nodeArrayList3.get(0);
        pinstrblocNode5 = (PInstrbloc)nodeArrayList4.get(0);
        tsinonNode6 = (TSinon)nodeArrayList5.get(0);
        pinstrblocNode7 = (PInstrbloc)nodeArrayList6.get(0);

        pinstrNode1 = new ASinonInstr(tsiNode2, pexpNode3, talorsNode4, pinstrblocNode5, tsinonNode6, pinstrblocNode7);
        }
	nodeList.add(pinstrNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new30() /* reduce ARetourInstr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInstr pinstrNode1;
        {
            // Block
        TRetour tretourNode2;
        PExp pexpNode3;
        TPointVirgule tpointvirguleNode4;
        tretourNode2 = (TRetour)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        tpointvirguleNode4 = (TPointVirgule)nodeArrayList3.get(0);

        pinstrNode1 = new ARetourInstr(tretourNode2, pexpNode3, tpointvirguleNode4);
        }
	nodeList.add(pinstrNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new31() /* reduce AEcrireInstr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInstr pinstrNode1;
        {
            // Block
        TEcrire tecrireNode2;
        TLPar tlparNode3;
        PExp pexpNode4;
        TRPar trparNode5;
        TPointVirgule tpointvirguleNode6;
        tecrireNode2 = (TEcrire)nodeArrayList1.get(0);
        tlparNode3 = (TLPar)nodeArrayList2.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);
        trparNode5 = (TRPar)nodeArrayList4.get(0);
        tpointvirguleNode6 = (TPointVirgule)nodeArrayList5.get(0);

        pinstrNode1 = new AEcrireInstr(tecrireNode2, tlparNode3, pexpNode4, trparNode5, tpointvirguleNode6);
        }
	nodeList.add(pinstrNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new32() /* reduce AListedinstrInstrbloc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInstrbloc pinstrblocNode1;
        {
            // Block
        TLAccolade tlaccoladeNode2;
        PListeinstr plisteinstrNode3;
        TRAccolade traccoladeNode4;
        tlaccoladeNode2 = (TLAccolade)nodeArrayList1.get(0);
        plisteinstrNode3 = (PListeinstr)nodeArrayList2.get(0);
        traccoladeNode4 = (TRAccolade)nodeArrayList3.get(0);

        pinstrblocNode1 = new AListedinstrInstrbloc(tlaccoladeNode2, plisteinstrNode3, traccoladeNode4);
        }
	nodeList.add(pinstrblocNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new33() /* reduce AListdeinstrListeinstr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PListeinstr plisteinstrNode1;
        {
            // Block
        PInstr pinstrNode2;
        PListeinstr plisteinstrNode3;
        pinstrNode2 = (PInstr)nodeArrayList1.get(0);
        plisteinstrNode3 = (PListeinstr)nodeArrayList2.get(0);

        plisteinstrNode1 = new AListdeinstrListeinstr(pinstrNode2, plisteinstrNode3);
        }
	nodeList.add(plisteinstrNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new34() /* reduce AEpsilonListeinstr */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PListeinstr plisteinstrNode1;
        {
            // Block

        plisteinstrNode1 = new AEpsilonListeinstr();
        }
	nodeList.add(plisteinstrNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new35() /* reduce AListedeexpressionListeexp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PListeexp plisteexpNode1;
        {
            // Block
        PExp pexpNode2;
        PListeexpbis plisteexpbisNode3;
        pexpNode2 = (PExp)nodeArrayList1.get(0);
        plisteexpbisNode3 = (PListeexpbis)nodeArrayList2.get(0);

        plisteexpNode1 = new AListedeexpressionListeexp(pexpNode2, plisteexpbisNode3);
        }
	nodeList.add(plisteexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new36() /* reduce AEpsilonListeexp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PListeexp plisteexpNode1;
        {
            // Block

        plisteexpNode1 = new AEpsilonListeexp();
        }
	nodeList.add(plisteexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new37() /* reduce ARestelistedeexpressionListeexpbis */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PListeexpbis plisteexpbisNode1;
        {
            // Block
        TVirgule tvirguleNode2;
        PExp pexpNode3;
        PListeexpbis plisteexpbisNode4;
        tvirguleNode2 = (TVirgule)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        plisteexpbisNode4 = (PListeexpbis)nodeArrayList3.get(0);

        plisteexpbisNode1 = new ARestelistedeexpressionListeexpbis(tvirguleNode2, pexpNode3, plisteexpbisNode4);
        }
	nodeList.add(plisteexpbisNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new38() /* reduce AEpsilonListeexpbis */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PListeexpbis plisteexpbisNode1;
        {
            // Block

        plisteexpbisNode1 = new AEpsilonListeexpbis();
        }
	nodeList.add(plisteexpbisNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new39() /* reduce AIdentifVar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PVar pvarNode1;
        {
            // Block
        TIdentif tidentifNode2;
        tidentifNode2 = (TIdentif)nodeArrayList1.get(0);

        pvarNode1 = new AIdentifVar(tidentifNode2);
        }
	nodeList.add(pvarNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new40() /* reduce AVarindexeeVar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PVar pvarNode1;
        {
            // Block
        TIdentif tidentifNode2;
        TBrackopen tbrackopenNode3;
        PExp pexpNode4;
        TBrackclose tbrackcloseNode5;
        tidentifNode2 = (TIdentif)nodeArrayList1.get(0);
        tbrackopenNode3 = (TBrackopen)nodeArrayList2.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);
        tbrackcloseNode5 = (TBrackclose)nodeArrayList4.get(0);

        pvarNode1 = new AVarindexeeVar(tidentifNode2, tbrackopenNode3, pexpNode4, tbrackcloseNode5);
        }
	nodeList.add(pvarNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new41() /* reduce ADeclarationvarDecvar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecvar pdecvarNode1;
        {
            // Block
        PType ptypeNode2;
        TIdentif tidentifNode3;
        ptypeNode2 = (PType)nodeArrayList1.get(0);
        tidentifNode3 = (TIdentif)nodeArrayList2.get(0);

        pdecvarNode1 = new ADeclarationvarDecvar(ptypeNode2, tidentifNode3);
        }
	nodeList.add(pdecvarNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new42() /* reduce ADeclarationvarindexeeDecvar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecvar pdecvarNode1;
        {
            // Block
        PType ptypeNode2;
        TIdentif tidentifNode3;
        TBrackopen tbrackopenNode4;
        TNumber tnumberNode5;
        TBrackclose tbrackcloseNode6;
        ptypeNode2 = (PType)nodeArrayList1.get(0);
        tidentifNode3 = (TIdentif)nodeArrayList2.get(0);
        tbrackopenNode4 = (TBrackopen)nodeArrayList3.get(0);
        tnumberNode5 = (TNumber)nodeArrayList4.get(0);
        tbrackcloseNode6 = (TBrackclose)nodeArrayList5.get(0);

        pdecvarNode1 = new ADeclarationvarindexeeDecvar(ptypeNode2, tidentifNode3, tbrackopenNode4, tnumberNode5, tbrackcloseNode6);
        }
	nodeList.add(pdecvarNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new43() /* reduce AEntierType */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TEntier tentierNode2;
        tentierNode2 = (TEntier)nodeArrayList1.get(0);

        ptypeNode1 = new AEntierType(tentierNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new44() /* reduce ABoolType */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PType ptypeNode1;
        {
            // Block
        TBool tboolNode2;
        tboolNode2 = (TBool)nodeArrayList1.get(0);

        ptypeNode1 = new ABoolType(tboolNode2);
        }
	nodeList.add(ptypeNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new45() /* reduce ADeclarationfonction$Listedecvar1$Listedecvar2$Type1Decfonc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList9 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecfonc pdecfoncNode1;
        {
            // Block
        POpttype popttypeNode2;
        TIdentif tidentifNode4;
        TLPar tlparNode5;
        PListedecvar plistedecvarNode6;
        TRPar trparNode9;
        PListedecvar plistedecvarNode10;
        PInstrbloc pinstrblocNode13;
        {
            // Block
        PType ptypeNode3;
        ptypeNode3 = (PType)nodeArrayList1.get(0);

        popttypeNode2 = new ATypeOpttype(ptypeNode3);
        }
        tidentifNode4 = (TIdentif)nodeArrayList2.get(0);
        tlparNode5 = (TLPar)nodeArrayList3.get(0);
        {
            // Block
        PDecvar pdecvarNode7;
        PListedecvarbis plistedecvarbisNode8;
        pdecvarNode7 = (PDecvar)nodeArrayList4.get(0);
        plistedecvarbisNode8 = (PListedecvarbis)nodeArrayList5.get(0);

        plistedecvarNode6 = new AListedecvarListedecvar(pdecvarNode7, plistedecvarbisNode8);
        }
        trparNode9 = (TRPar)nodeArrayList6.get(0);
        {
            // Block
        PDecvar pdecvarNode11;
        PListedecvarbis plistedecvarbisNode12;
        pdecvarNode11 = (PDecvar)nodeArrayList7.get(0);
        plistedecvarbisNode12 = (PListedecvarbis)nodeArrayList8.get(0);

        plistedecvarNode10 = new AListedecvarListedecvar(pdecvarNode11, plistedecvarbisNode12);
        }
        pinstrblocNode13 = (PInstrbloc)nodeArrayList9.get(0);

        pdecfoncNode1 = new ADeclarationfonctionDecfonc(popttypeNode2, tidentifNode4, tlparNode5, plistedecvarNode6, trparNode9, plistedecvarNode10, pinstrblocNode13);
        }
	nodeList.add(pdecfoncNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new46() /* reduce ADeclarationfonction$Listedecvar1$Listedecvar2$Epsilon1Decfonc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList8 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecfonc pdecfoncNode1;
        {
            // Block
        POpttype popttypeNode2;
        TIdentif tidentifNode3;
        TLPar tlparNode4;
        PListedecvar plistedecvarNode5;
        TRPar trparNode8;
        PListedecvar plistedecvarNode9;
        PInstrbloc pinstrblocNode12;
        {
            // Block

        popttypeNode2 = new AEpsilonOpttype();
        }
        tidentifNode3 = (TIdentif)nodeArrayList1.get(0);
        tlparNode4 = (TLPar)nodeArrayList2.get(0);
        {
            // Block
        PDecvar pdecvarNode6;
        PListedecvarbis plistedecvarbisNode7;
        pdecvarNode6 = (PDecvar)nodeArrayList3.get(0);
        plistedecvarbisNode7 = (PListedecvarbis)nodeArrayList4.get(0);

        plistedecvarNode5 = new AListedecvarListedecvar(pdecvarNode6, plistedecvarbisNode7);
        }
        trparNode8 = (TRPar)nodeArrayList5.get(0);
        {
            // Block
        PDecvar pdecvarNode10;
        PListedecvarbis plistedecvarbisNode11;
        pdecvarNode10 = (PDecvar)nodeArrayList6.get(0);
        plistedecvarbisNode11 = (PListedecvarbis)nodeArrayList7.get(0);

        plistedecvarNode9 = new AListedecvarListedecvar(pdecvarNode10, plistedecvarbisNode11);
        }
        pinstrblocNode12 = (PInstrbloc)nodeArrayList8.get(0);

        pdecfoncNode1 = new ADeclarationfonctionDecfonc(popttypeNode2, tidentifNode3, tlparNode4, plistedecvarNode5, trparNode8, plistedecvarNode9, pinstrblocNode12);
        }
	nodeList.add(pdecfoncNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new47() /* reduce ADeclarationfonction$Listedecvar1$Epsilon2$Type1Decfonc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecfonc pdecfoncNode1;
        {
            // Block
        POpttype popttypeNode2;
        TIdentif tidentifNode4;
        TLPar tlparNode5;
        PListedecvar plistedecvarNode6;
        TRPar trparNode9;
        PListedecvar plistedecvarNode10;
        PInstrbloc pinstrblocNode11;
        {
            // Block
        PType ptypeNode3;
        ptypeNode3 = (PType)nodeArrayList1.get(0);

        popttypeNode2 = new ATypeOpttype(ptypeNode3);
        }
        tidentifNode4 = (TIdentif)nodeArrayList2.get(0);
        tlparNode5 = (TLPar)nodeArrayList3.get(0);
        {
            // Block
        PDecvar pdecvarNode7;
        PListedecvarbis plistedecvarbisNode8;
        pdecvarNode7 = (PDecvar)nodeArrayList4.get(0);
        plistedecvarbisNode8 = (PListedecvarbis)nodeArrayList5.get(0);

        plistedecvarNode6 = new AListedecvarListedecvar(pdecvarNode7, plistedecvarbisNode8);
        }
        trparNode9 = (TRPar)nodeArrayList6.get(0);
        {
            // Block

        plistedecvarNode10 = new AEpsilonListedecvar();
        }
        pinstrblocNode11 = (PInstrbloc)nodeArrayList7.get(0);

        pdecfoncNode1 = new ADeclarationfonctionDecfonc(popttypeNode2, tidentifNode4, tlparNode5, plistedecvarNode6, trparNode9, plistedecvarNode10, pinstrblocNode11);
        }
	nodeList.add(pdecfoncNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new48() /* reduce ADeclarationfonction$Listedecvar1$Epsilon2$Epsilon1Decfonc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecfonc pdecfoncNode1;
        {
            // Block
        POpttype popttypeNode2;
        TIdentif tidentifNode3;
        TLPar tlparNode4;
        PListedecvar plistedecvarNode5;
        TRPar trparNode8;
        PListedecvar plistedecvarNode9;
        PInstrbloc pinstrblocNode10;
        {
            // Block

        popttypeNode2 = new AEpsilonOpttype();
        }
        tidentifNode3 = (TIdentif)nodeArrayList1.get(0);
        tlparNode4 = (TLPar)nodeArrayList2.get(0);
        {
            // Block
        PDecvar pdecvarNode6;
        PListedecvarbis plistedecvarbisNode7;
        pdecvarNode6 = (PDecvar)nodeArrayList3.get(0);
        plistedecvarbisNode7 = (PListedecvarbis)nodeArrayList4.get(0);

        plistedecvarNode5 = new AListedecvarListedecvar(pdecvarNode6, plistedecvarbisNode7);
        }
        trparNode8 = (TRPar)nodeArrayList5.get(0);
        {
            // Block

        plistedecvarNode9 = new AEpsilonListedecvar();
        }
        pinstrblocNode10 = (PInstrbloc)nodeArrayList6.get(0);

        pdecfoncNode1 = new ADeclarationfonctionDecfonc(popttypeNode2, tidentifNode3, tlparNode4, plistedecvarNode5, trparNode8, plistedecvarNode9, pinstrblocNode10);
        }
	nodeList.add(pdecfoncNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new49() /* reduce ADeclarationfonction$Epsilon1$Listedecvar2$Type1Decfonc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecfonc pdecfoncNode1;
        {
            // Block
        POpttype popttypeNode2;
        TIdentif tidentifNode4;
        TLPar tlparNode5;
        PListedecvar plistedecvarNode6;
        TRPar trparNode7;
        PListedecvar plistedecvarNode8;
        PInstrbloc pinstrblocNode11;
        {
            // Block
        PType ptypeNode3;
        ptypeNode3 = (PType)nodeArrayList1.get(0);

        popttypeNode2 = new ATypeOpttype(ptypeNode3);
        }
        tidentifNode4 = (TIdentif)nodeArrayList2.get(0);
        tlparNode5 = (TLPar)nodeArrayList3.get(0);
        {
            // Block

        plistedecvarNode6 = new AEpsilonListedecvar();
        }
        trparNode7 = (TRPar)nodeArrayList4.get(0);
        {
            // Block
        PDecvar pdecvarNode9;
        PListedecvarbis plistedecvarbisNode10;
        pdecvarNode9 = (PDecvar)nodeArrayList5.get(0);
        plistedecvarbisNode10 = (PListedecvarbis)nodeArrayList6.get(0);

        plistedecvarNode8 = new AListedecvarListedecvar(pdecvarNode9, plistedecvarbisNode10);
        }
        pinstrblocNode11 = (PInstrbloc)nodeArrayList7.get(0);

        pdecfoncNode1 = new ADeclarationfonctionDecfonc(popttypeNode2, tidentifNode4, tlparNode5, plistedecvarNode6, trparNode7, plistedecvarNode8, pinstrblocNode11);
        }
	nodeList.add(pdecfoncNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new50() /* reduce ADeclarationfonction$Epsilon1$Listedecvar2$Epsilon1Decfonc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecfonc pdecfoncNode1;
        {
            // Block
        POpttype popttypeNode2;
        TIdentif tidentifNode3;
        TLPar tlparNode4;
        PListedecvar plistedecvarNode5;
        TRPar trparNode6;
        PListedecvar plistedecvarNode7;
        PInstrbloc pinstrblocNode10;
        {
            // Block

        popttypeNode2 = new AEpsilonOpttype();
        }
        tidentifNode3 = (TIdentif)nodeArrayList1.get(0);
        tlparNode4 = (TLPar)nodeArrayList2.get(0);
        {
            // Block

        plistedecvarNode5 = new AEpsilonListedecvar();
        }
        trparNode6 = (TRPar)nodeArrayList3.get(0);
        {
            // Block
        PDecvar pdecvarNode8;
        PListedecvarbis plistedecvarbisNode9;
        pdecvarNode8 = (PDecvar)nodeArrayList4.get(0);
        plistedecvarbisNode9 = (PListedecvarbis)nodeArrayList5.get(0);

        plistedecvarNode7 = new AListedecvarListedecvar(pdecvarNode8, plistedecvarbisNode9);
        }
        pinstrblocNode10 = (PInstrbloc)nodeArrayList6.get(0);

        pdecfoncNode1 = new ADeclarationfonctionDecfonc(popttypeNode2, tidentifNode3, tlparNode4, plistedecvarNode5, trparNode6, plistedecvarNode7, pinstrblocNode10);
        }
	nodeList.add(pdecfoncNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new51() /* reduce ADeclarationfonction$Epsilon1$Epsilon2$Type1Decfonc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecfonc pdecfoncNode1;
        {
            // Block
        POpttype popttypeNode2;
        TIdentif tidentifNode4;
        TLPar tlparNode5;
        PListedecvar plistedecvarNode6;
        TRPar trparNode7;
        PListedecvar plistedecvarNode8;
        PInstrbloc pinstrblocNode9;
        {
            // Block
        PType ptypeNode3;
        ptypeNode3 = (PType)nodeArrayList1.get(0);

        popttypeNode2 = new ATypeOpttype(ptypeNode3);
        }
        tidentifNode4 = (TIdentif)nodeArrayList2.get(0);
        tlparNode5 = (TLPar)nodeArrayList3.get(0);
        {
            // Block

        plistedecvarNode6 = new AEpsilonListedecvar();
        }
        trparNode7 = (TRPar)nodeArrayList4.get(0);
        {
            // Block

        plistedecvarNode8 = new AEpsilonListedecvar();
        }
        pinstrblocNode9 = (PInstrbloc)nodeArrayList5.get(0);

        pdecfoncNode1 = new ADeclarationfonctionDecfonc(popttypeNode2, tidentifNode4, tlparNode5, plistedecvarNode6, trparNode7, plistedecvarNode8, pinstrblocNode9);
        }
	nodeList.add(pdecfoncNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new52() /* reduce ADeclarationfonction$Epsilon1$Epsilon2$Epsilon1Decfonc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecfonc pdecfoncNode1;
        {
            // Block
        POpttype popttypeNode2;
        TIdentif tidentifNode3;
        TLPar tlparNode4;
        PListedecvar plistedecvarNode5;
        TRPar trparNode6;
        PListedecvar plistedecvarNode7;
        PInstrbloc pinstrblocNode8;
        {
            // Block

        popttypeNode2 = new AEpsilonOpttype();
        }
        tidentifNode3 = (TIdentif)nodeArrayList1.get(0);
        tlparNode4 = (TLPar)nodeArrayList2.get(0);
        {
            // Block

        plistedecvarNode5 = new AEpsilonListedecvar();
        }
        trparNode6 = (TRPar)nodeArrayList3.get(0);
        {
            // Block

        plistedecvarNode7 = new AEpsilonListedecvar();
        }
        pinstrblocNode8 = (PInstrbloc)nodeArrayList4.get(0);

        pdecfoncNode1 = new ADeclarationfonctionDecfonc(popttypeNode2, tidentifNode3, tlparNode4, plistedecvarNode5, trparNode6, plistedecvarNode7, pinstrblocNode8);
        }
	nodeList.add(pdecfoncNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new53() /* reduce AApreslistedecvarListedecvarbis */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PListedecvarbis plistedecvarbisNode1;
        {
            // Block
        TVirgule tvirguleNode2;
        PDecvar pdecvarNode3;
        PListedecvarbis plistedecvarbisNode4;
        tvirguleNode2 = (TVirgule)nodeArrayList1.get(0);
        pdecvarNode3 = (PDecvar)nodeArrayList2.get(0);
        plistedecvarbisNode4 = (PListedecvarbis)nodeArrayList3.get(0);

        plistedecvarbisNode1 = new AApreslistedecvarListedecvarbis(tvirguleNode2, pdecvarNode3, plistedecvarbisNode4);
        }
	nodeList.add(plistedecvarbisNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new54() /* reduce AEpsilonListedecvarbis */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PListedecvarbis plistedecvarbisNode1;
        {
            // Block

        plistedecvarbisNode1 = new AEpsilonListedecvarbis();
        }
	nodeList.add(plistedecvarbisNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new55() /* reduce AListedecfoncListedecfonc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PListedecfonc plistedecfoncNode1;
        {
            // Block
        PDecfonc pdecfoncNode2;
        PListedecfonc plistedecfoncNode3;
        pdecfoncNode2 = (PDecfonc)nodeArrayList1.get(0);
        plistedecfoncNode3 = (PListedecfonc)nodeArrayList2.get(0);

        plistedecfoncNode1 = new AListedecfoncListedecfonc(pdecfoncNode2, plistedecfoncNode3);
        }
	nodeList.add(plistedecfoncNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new56() /* reduce AEpsilonListedecfonc */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PListedecfonc plistedecfoncNode1;
        {
            // Block

        plistedecfoncNode1 = new AEpsilonListedecfonc();
        }
	nodeList.add(plistedecfoncNode1);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, REDUCE, 56}, {32, SHIFT, 1}, {33, SHIFT, 2}, {34, SHIFT, 3}, },
			{{-1, REDUCE, 43}, },
			{{-1, REDUCE, 44}, },
			{{-1, ERROR, 3}, {2, SHIFT, 9}, },
			{{-1, ERROR, 4}, {35, ACCEPT, -1}, },
			{{-1, REDUCE, 54}, {22, SHIFT, 10}, },
			{{-1, ERROR, 6}, {34, SHIFT, 12}, },
			{{-1, REDUCE, 56}, {32, SHIFT, 1}, {33, SHIFT, 2}, {34, SHIFT, 3}, },
			{{-1, REDUCE, 1}, },
			{{-1, ERROR, 9}, {3, SHIFT, 15}, {32, SHIFT, 1}, {33, SHIFT, 2}, },
			{{-1, ERROR, 10}, {32, SHIFT, 1}, {33, SHIFT, 2}, },
			{{-1, REDUCE, 56}, {32, SHIFT, 1}, {33, SHIFT, 2}, {34, SHIFT, 3}, },
			{{-1, REDUCE, 41}, {2, SHIFT, 20}, {19, SHIFT, 21}, },
			{{-1, ERROR, 13}, {34, SHIFT, 22}, },
			{{-1, REDUCE, 55}, },
			{{-1, ERROR, 15}, {0, SHIFT, 23}, {32, SHIFT, 1}, {33, SHIFT, 2}, },
			{{-1, REDUCE, 54}, {22, SHIFT, 10}, },
			{{-1, ERROR, 17}, {34, SHIFT, 27}, },
			{{-1, REDUCE, 54}, {22, SHIFT, 10}, },
			{{-1, REDUCE, 0}, },
			{{-1, ERROR, 20}, {3, SHIFT, 29}, {32, SHIFT, 1}, {33, SHIFT, 2}, },
			{{-1, ERROR, 21}, {31, SHIFT, 31}, },
			{{-1, ERROR, 22}, {2, SHIFT, 20}, },
			{{-1, REDUCE, 34}, {23, SHIFT, 32}, {25, SHIFT, 33}, {26, SHIFT, 34}, {29, SHIFT, 35}, {34, SHIFT, 36}, },
			{{-1, REDUCE, 52}, },
			{{-1, REDUCE, 54}, {22, SHIFT, 10}, },
			{{-1, ERROR, 26}, {3, SHIFT, 41}, },
			{{-1, REDUCE, 41}, {19, SHIFT, 21}, },
			{{-1, REDUCE, 53}, },
			{{-1, ERROR, 29}, {0, SHIFT, 23}, {32, SHIFT, 1}, {33, SHIFT, 2}, },
			{{-1, REDUCE, 54}, {22, SHIFT, 10}, },
			{{-1, ERROR, 31}, {20, SHIFT, 45}, },
			{{-1, ERROR, 32}, {2, SHIFT, 46}, {4, SHIFT, 47}, {9, SHIFT, 48}, {10, SHIFT, 49}, {24, SHIFT, 50}, {31, SHIFT, 51}, {34, SHIFT, 52}, },
			{{-1, ERROR, 33}, {2, SHIFT, 62}, },
			{{-1, ERROR, 34}, {2, SHIFT, 46}, {4, SHIFT, 47}, {9, SHIFT, 48}, {10, SHIFT, 49}, {24, SHIFT, 50}, {31, SHIFT, 51}, {34, SHIFT, 52}, },
			{{-1, ERROR, 35}, {2, SHIFT, 46}, {4, SHIFT, 47}, {9, SHIFT, 48}, {10, SHIFT, 49}, {24, SHIFT, 50}, {31, SHIFT, 51}, {34, SHIFT, 52}, },
			{{-1, REDUCE, 39}, {2, SHIFT, 65}, {19, SHIFT, 66}, },
			{{-1, REDUCE, 34}, {23, SHIFT, 32}, {25, SHIFT, 33}, {26, SHIFT, 34}, {29, SHIFT, 35}, {34, SHIFT, 36}, },
			{{-1, ERROR, 38}, {1, SHIFT, 68}, },
			{{-1, ERROR, 39}, {11, SHIFT, 69}, },
			{{-1, ERROR, 40}, {0, SHIFT, 23}, },
			{{-1, ERROR, 41}, {0, SHIFT, 23}, {32, SHIFT, 1}, {33, SHIFT, 2}, },
			{{-1, REDUCE, 51}, },
			{{-1, REDUCE, 54}, {22, SHIFT, 10}, },
			{{-1, ERROR, 44}, {3, SHIFT, 74}, },
			{{-1, REDUCE, 42}, },
			{{-1, ERROR, 46}, {2, SHIFT, 46}, {4, SHIFT, 47}, {9, SHIFT, 48}, {10, SHIFT, 49}, {24, SHIFT, 50}, {31, SHIFT, 51}, {34, SHIFT, 52}, },
			{{-1, ERROR, 47}, {2, SHIFT, 46}, {4, SHIFT, 47}, {9, SHIFT, 48}, {10, SHIFT, 49}, {24, SHIFT, 50}, {31, SHIFT, 51}, {34, SHIFT, 52}, },
			{{-1, REDUCE, 19}, },
			{{-1, REDUCE, 20}, },
			{{-1, ERROR, 50}, {2, SHIFT, 77}, },
			{{-1, REDUCE, 18}, },
			{{-1, REDUCE, 39}, {2, SHIFT, 78}, {19, SHIFT, 66}, },
			{{-1, ERROR, 53}, {14, SHIFT, 79}, {18, SHIFT, 80}, },
			{{-1, REDUCE, 3}, {13, SHIFT, 81}, },
			{{-1, REDUCE, 5}, {11, SHIFT, 82}, {12, SHIFT, 83}, },
			{{-1, REDUCE, 8}, {7, SHIFT, 84}, {8, SHIFT, 85}, },
			{{-1, REDUCE, 11}, {5, SHIFT, 86}, {6, SHIFT, 87}, },
			{{-1, REDUCE, 14}, },
			{{-1, REDUCE, 16}, },
			{{-1, REDUCE, 22}, },
			{{-1, REDUCE, 21}, },
			{{-1, ERROR, 62}, {2, SHIFT, 46}, {4, SHIFT, 47}, {9, SHIFT, 48}, {10, SHIFT, 49}, {24, SHIFT, 50}, {31, SHIFT, 51}, {34, SHIFT, 52}, },
			{{-1, ERROR, 63}, {14, SHIFT, 79}, {28, SHIFT, 89}, },
			{{-1, ERROR, 64}, {14, SHIFT, 79}, {30, SHIFT, 90}, },
			{{-1, REDUCE, 36}, {2, SHIFT, 46}, {4, SHIFT, 47}, {9, SHIFT, 48}, {10, SHIFT, 49}, {24, SHIFT, 50}, {31, SHIFT, 51}, {34, SHIFT, 52}, },
			{{-1, ERROR, 66}, {2, SHIFT, 46}, {4, SHIFT, 47}, {9, SHIFT, 48}, {10, SHIFT, 49}, {24, SHIFT, 50}, {31, SHIFT, 51}, {34, SHIFT, 52}, },
			{{-1, REDUCE, 33}, },
			{{-1, REDUCE, 32}, },
			{{-1, ERROR, 69}, {2, SHIFT, 46}, {4, SHIFT, 47}, {9, SHIFT, 48}, {10, SHIFT, 49}, {24, SHIFT, 50}, {31, SHIFT, 51}, {34, SHIFT, 52}, },
			{{-1, REDUCE, 50}, },
			{{-1, REDUCE, 48}, },
			{{-1, REDUCE, 54}, {22, SHIFT, 10}, },
			{{-1, ERROR, 73}, {0, SHIFT, 23}, },
			{{-1, ERROR, 74}, {0, SHIFT, 23}, {32, SHIFT, 1}, {33, SHIFT, 2}, },
			{{-1, ERROR, 75}, {3, SHIFT, 99}, {14, SHIFT, 79}, },
			{{-1, REDUCE, 15}, },
			{{-1, ERROR, 77}, {3, SHIFT, 100}, },
			{{-1, REDUCE, 36}, {2, SHIFT, 46}, {4, SHIFT, 47}, {9, SHIFT, 48}, {10, SHIFT, 49}, {24, SHIFT, 50}, {31, SHIFT, 51}, {34, SHIFT, 52}, },
			{{-1, ERROR, 79}, {2, SHIFT, 46}, {4, SHIFT, 47}, {9, SHIFT, 48}, {10, SHIFT, 49}, {24, SHIFT, 50}, {31, SHIFT, 51}, {34, SHIFT, 52}, },
			{{-1, REDUCE, 30}, },
			{{-1, ERROR, 81}, {2, SHIFT, 46}, {4, SHIFT, 47}, {9, SHIFT, 48}, {10, SHIFT, 49}, {24, SHIFT, 50}, {31, SHIFT, 51}, {34, SHIFT, 52}, },
			{{-1, ERROR, 82}, {2, SHIFT, 46}, {4, SHIFT, 47}, {9, SHIFT, 48}, {10, SHIFT, 49}, {24, SHIFT, 50}, {31, SHIFT, 51}, {34, SHIFT, 52}, },
			{{-1, ERROR, 83}, {2, SHIFT, 46}, {4, SHIFT, 47}, {9, SHIFT, 48}, {10, SHIFT, 49}, {24, SHIFT, 50}, {31, SHIFT, 51}, {34, SHIFT, 52}, },
			{{-1, ERROR, 84}, {2, SHIFT, 46}, {4, SHIFT, 47}, {9, SHIFT, 48}, {10, SHIFT, 49}, {24, SHIFT, 50}, {31, SHIFT, 51}, {34, SHIFT, 52}, },
			{{-1, ERROR, 85}, {2, SHIFT, 46}, {4, SHIFT, 47}, {9, SHIFT, 48}, {10, SHIFT, 49}, {24, SHIFT, 50}, {31, SHIFT, 51}, {34, SHIFT, 52}, },
			{{-1, ERROR, 86}, {2, SHIFT, 46}, {4, SHIFT, 47}, {9, SHIFT, 48}, {10, SHIFT, 49}, {24, SHIFT, 50}, {31, SHIFT, 51}, {34, SHIFT, 52}, },
			{{-1, ERROR, 87}, {2, SHIFT, 46}, {4, SHIFT, 47}, {9, SHIFT, 48}, {10, SHIFT, 49}, {24, SHIFT, 50}, {31, SHIFT, 51}, {34, SHIFT, 52}, },
			{{-1, ERROR, 88}, {3, SHIFT, 110}, {14, SHIFT, 79}, },
			{{-1, ERROR, 89}, {0, SHIFT, 23}, },
			{{-1, ERROR, 90}, {0, SHIFT, 23}, },
			{{-1, REDUCE, 38}, {14, SHIFT, 79}, {22, SHIFT, 113}, },
			{{-1, ERROR, 92}, {3, SHIFT, 115}, },
			{{-1, ERROR, 93}, {14, SHIFT, 79}, {20, SHIFT, 116}, },
			{{-1, ERROR, 94}, {14, SHIFT, 79}, {18, SHIFT, 117}, },
			{{-1, ERROR, 95}, {0, SHIFT, 23}, },
			{{-1, REDUCE, 49}, },
			{{-1, REDUCE, 47}, },
			{{-1, REDUCE, 54}, {22, SHIFT, 10}, },
			{{-1, REDUCE, 17}, },
			{{-1, REDUCE, 23}, },
			{{-1, ERROR, 101}, {3, SHIFT, 120}, },
			{{-1, REDUCE, 2}, {13, SHIFT, 81}, },
			{{-1, REDUCE, 4}, {11, SHIFT, 82}, {12, SHIFT, 83}, },
			{{-1, REDUCE, 6}, {7, SHIFT, 84}, {8, SHIFT, 85}, },
			{{-1, REDUCE, 7}, {7, SHIFT, 84}, {8, SHIFT, 85}, },
			{{-1, REDUCE, 9}, {5, SHIFT, 86}, {6, SHIFT, 87}, },
			{{-1, REDUCE, 10}, {5, SHIFT, 86}, {6, SHIFT, 87}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 13}, },
			{{-1, ERROR, 110}, {18, SHIFT, 121}, },
			{{-1, REDUCE, 28}, {27, SHIFT, 122}, },
			{{-1, REDUCE, 26}, },
			{{-1, ERROR, 113}, {2, SHIFT, 46}, {4, SHIFT, 47}, {9, SHIFT, 48}, {10, SHIFT, 49}, {24, SHIFT, 50}, {31, SHIFT, 51}, {34, SHIFT, 52}, },
			{{-1, REDUCE, 35}, },
			{{-1, ERROR, 115}, {18, SHIFT, 124}, },
			{{-1, REDUCE, 40}, },
			{{-1, REDUCE, 25}, },
			{{-1, REDUCE, 46}, },
			{{-1, ERROR, 119}, {0, SHIFT, 23}, },
			{{-1, REDUCE, 24}, },
			{{-1, REDUCE, 31}, },
			{{-1, ERROR, 122}, {0, SHIFT, 23}, },
			{{-1, REDUCE, 38}, {14, SHIFT, 79}, {22, SHIFT, 113}, },
			{{-1, REDUCE, 27}, },
			{{-1, REDUCE, 45}, },
			{{-1, REDUCE, 29}, },
			{{-1, REDUCE, 37}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 4}, },
			{{-1, 91}, {32, 53}, {34, 63}, {35, 64}, {46, 75}, {62, 88}, {66, 93}, {69, 94}, {113, 123}, },
			{{-1, 54}, {79, 102}, },
			{{-1, 55}, {81, 103}, },
			{{-1, 56}, {82, 104}, {83, 105}, },
			{{-1, 57}, {84, 106}, {85, 107}, },
			{{-1, 58}, {47, 76}, {86, 108}, {87, 109}, },
			{{-1, 59}, },
			{{-1, 60}, },
			{{-1, 37}, },
			{{-1, 24}, {29, 42}, {40, 70}, {41, 71}, {73, 96}, {74, 97}, {89, 111}, {90, 112}, {95, 118}, {119, 125}, {122, 126}, },
			{{-1, 38}, {37, 67}, },
			{{-1, 92}, {78, 101}, },
			{{-1, 114}, {123, 127}, },
			{{-1, 61}, {23, 39}, {37, 39}, },
			{{-1, 5}, {9, 16}, {10, 18}, {15, 25}, {20, 30}, {29, 43}, {41, 72}, {74, 98}, },
			{{-1, 17}, {0, 6}, {7, 13}, {11, 13}, },
			{{-1, 7}, },
			{{-1, 11}, {16, 26}, {18, 28}, {25, 40}, {30, 44}, {43, 73}, {72, 95}, {98, 119}, },
			{{-1, 8}, {7, 14}, {11, 19}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: 'entier', 'bool', identif, EOF",
			"expecting: identif",
			"expecting: '('",
			"expecting: EOF",
			"expecting: ',', 'entier', 'bool', identif, EOF",
			"expecting: ')', 'entier', 'bool'",
			"expecting: 'entier', 'bool'",
			"expecting: '(', '[', ',', 'entier', 'bool', identif, EOF",
			"expecting: '{', 'entier', 'bool'",
			"expecting: ')', ','",
			"expecting: '{', ')', ',', 'entier', 'bool', identif, EOF",
			"expecting: number",
			"expecting: '}', 'retour', 'ecrire', 'si', 'tantque', identif",
			"expecting: '{', ','",
			"expecting: ')'",
			"expecting: '{', ')', '[', ',', 'entier', 'bool', identif, EOF",
			"expecting: '{', ')', 'entier', 'bool', identif, EOF",
			"expecting: ']'",
			"expecting: '(', '!', 'vrai', 'faux', 'lire', number, identif",
			"expecting: '(', '=', '['",
			"expecting: '}'",
			"expecting: '='",
			"expecting: '{'",
			"expecting: ')', '*', '/', '+', '-', '=', '<', '&', '|', ';', ']', ',', 'alors', 'faire'",
			"expecting: '(', ')', '*', '/', '+', '-', '=', '<', '&', '|', ';', '[', ']', ',', 'alors', 'faire'",
			"expecting: '|', ';'",
			"expecting: ')', '&', '|', ';', ']', ',', 'alors', 'faire'",
			"expecting: ')', '=', '<', '&', '|', ';', ']', ',', 'alors', 'faire'",
			"expecting: ')', '+', '-', '=', '<', '&', '|', ';', ']', ',', 'alors', 'faire'",
			"expecting: '|', 'alors'",
			"expecting: '|', 'faire'",
			"expecting: '(', ')', '!', 'vrai', 'faux', 'lire', number, identif",
			"expecting: '}', 'retour', 'ecrire', 'si', 'sinon', 'tantque', 'entier', 'bool', identif, EOF",
			"expecting: ')', '|'",
			"expecting: ')', '|', ','",
			"expecting: '|', ']'",
			"expecting: ';'",
			"expecting: '}', 'retour', 'ecrire', 'si', 'sinon', 'tantque', identif",
        };*/
    private static int[] errors;
/*      {
			0, 1, 1, 2, 3, 4, 1, 0, 3, 5, 6, 0, 7, 1, 3, 8, 9, 1, 10, 3, 5, 11, 2, 12, 0, 13, 14, 15, 16, 8, 9, 17, 18, 2, 18, 18, 19, 12, 20, 21, 22, 8, 0, 13, 14, 10, 18, 18, 23, 23, 2, 23, 24, 25, 26, 27, 28, 23, 23, 23, 23, 23, 18, 29, 30, 31, 18, 20, 32, 18, 0, 0, 13, 22, 8, 33, 23, 14, 31, 18, 12, 18, 18, 18, 18, 18, 18, 18, 33, 22, 22, 34, 14, 35, 25, 22, 0, 0, 13, 23, 23, 14, 26, 27, 28, 28, 23, 23, 23, 23, 36, 37, 12, 18, 14, 36, 23, 12, 0, 22, 23, 12, 22, 34, 12, 0, 12, 14, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
