/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ADeclarationvarindexeeDecvar extends PDecvar
{
    private PType _type_;
    private TIdentif _identif_;
    private TBrackopen _brackopen_;
    private TNumber _number_;
    private TBrackclose _brackclose_;

    public ADeclarationvarindexeeDecvar()
    {
        // Constructor
    }

    public ADeclarationvarindexeeDecvar(
        @SuppressWarnings("hiding") PType _type_,
        @SuppressWarnings("hiding") TIdentif _identif_,
        @SuppressWarnings("hiding") TBrackopen _brackopen_,
        @SuppressWarnings("hiding") TNumber _number_,
        @SuppressWarnings("hiding") TBrackclose _brackclose_)
    {
        // Constructor
        setType(_type_);

        setIdentif(_identif_);

        setBrackopen(_brackopen_);

        setNumber(_number_);

        setBrackclose(_brackclose_);

    }

    @Override
    public Object clone()
    {
        return new ADeclarationvarindexeeDecvar(
            cloneNode(this._type_),
            cloneNode(this._identif_),
            cloneNode(this._brackopen_),
            cloneNode(this._number_),
            cloneNode(this._brackclose_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclarationvarindexeeDecvar(this);
    }

    public PType getType()
    {
        return this._type_;
    }

    public void setType(PType node)
    {
        if(this._type_ != null)
        {
            this._type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    public TIdentif getIdentif()
    {
        return this._identif_;
    }

    public void setIdentif(TIdentif node)
    {
        if(this._identif_ != null)
        {
            this._identif_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identif_ = node;
    }

    public TBrackopen getBrackopen()
    {
        return this._brackopen_;
    }

    public void setBrackopen(TBrackopen node)
    {
        if(this._brackopen_ != null)
        {
            this._brackopen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._brackopen_ = node;
    }

    public TNumber getNumber()
    {
        return this._number_;
    }

    public void setNumber(TNumber node)
    {
        if(this._number_ != null)
        {
            this._number_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._number_ = node;
    }

    public TBrackclose getBrackclose()
    {
        return this._brackclose_;
    }

    public void setBrackclose(TBrackclose node)
    {
        if(this._brackclose_ != null)
        {
            this._brackclose_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._brackclose_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._type_)
            + toString(this._identif_)
            + toString(this._brackopen_)
            + toString(this._number_)
            + toString(this._brackclose_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._type_ == child)
        {
            this._type_ = null;
            return;
        }

        if(this._identif_ == child)
        {
            this._identif_ = null;
            return;
        }

        if(this._brackopen_ == child)
        {
            this._brackopen_ = null;
            return;
        }

        if(this._number_ == child)
        {
            this._number_ = null;
            return;
        }

        if(this._brackclose_ == child)
        {
            this._brackclose_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        if(this._identif_ == oldChild)
        {
            setIdentif((TIdentif) newChild);
            return;
        }

        if(this._brackopen_ == oldChild)
        {
            setBrackopen((TBrackopen) newChild);
            return;
        }

        if(this._number_ == oldChild)
        {
            setNumber((TNumber) newChild);
            return;
        }

        if(this._brackclose_ == oldChild)
        {
            setBrackclose((TBrackclose) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
