/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ADivM extends PM
{
    private PM _m_;
    private TDiv _div_;
    private PN _n_;

    public ADivM()
    {
        // Constructor
    }

    public ADivM(
        @SuppressWarnings("hiding") PM _m_,
        @SuppressWarnings("hiding") TDiv _div_,
        @SuppressWarnings("hiding") PN _n_)
    {
        // Constructor
        setM(_m_);

        setDiv(_div_);

        setN(_n_);

    }

    @Override
    public Object clone()
    {
        return new ADivM(
            cloneNode(this._m_),
            cloneNode(this._div_),
            cloneNode(this._n_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivM(this);
    }

    public PM getM()
    {
        return this._m_;
    }

    public void setM(PM node)
    {
        if(this._m_ != null)
        {
            this._m_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._m_ = node;
    }

    public TDiv getDiv()
    {
        return this._div_;
    }

    public void setDiv(TDiv node)
    {
        if(this._div_ != null)
        {
            this._div_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._div_ = node;
    }

    public PN getN()
    {
        return this._n_;
    }

    public void setN(PN node)
    {
        if(this._n_ != null)
        {
            this._n_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._n_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._m_)
            + toString(this._div_)
            + toString(this._n_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._m_ == child)
        {
            this._m_ = null;
            return;
        }

        if(this._div_ == child)
        {
            this._div_ = null;
            return;
        }

        if(this._n_ == child)
        {
            this._n_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._m_ == oldChild)
        {
            setM((PM) newChild);
            return;
        }

        if(this._div_ == oldChild)
        {
            setDiv((TDiv) newChild);
            return;
        }

        if(this._n_ == oldChild)
        {
            setN((PN) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
