/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AEqualE extends PE
{
    private PE _e_;
    private TEqual _equal_;
    private PP _p_;

    public AEqualE()
    {
        // Constructor
    }

    public AEqualE(
        @SuppressWarnings("hiding") PE _e_,
        @SuppressWarnings("hiding") TEqual _equal_,
        @SuppressWarnings("hiding") PP _p_)
    {
        // Constructor
        setE(_e_);

        setEqual(_equal_);

        setP(_p_);

    }

    @Override
    public Object clone()
    {
        return new AEqualE(
            cloneNode(this._e_),
            cloneNode(this._equal_),
            cloneNode(this._p_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqualE(this);
    }

    public PE getE()
    {
        return this._e_;
    }

    public void setE(PE node)
    {
        if(this._e_ != null)
        {
            this._e_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e_ = node;
    }

    public TEqual getEqual()
    {
        return this._equal_;
    }

    public void setEqual(TEqual node)
    {
        if(this._equal_ != null)
        {
            this._equal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equal_ = node;
    }

    public PP getP()
    {
        return this._p_;
    }

    public void setP(PP node)
    {
        if(this._p_ != null)
        {
            this._p_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._p_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._e_)
            + toString(this._equal_)
            + toString(this._p_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._e_ == child)
        {
            this._e_ = null;
            return;
        }

        if(this._equal_ == child)
        {
            this._equal_ = null;
            return;
        }

        if(this._p_ == child)
        {
            this._p_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._e_ == oldChild)
        {
            setE((PE) newChild);
            return;
        }

        if(this._equal_ == oldChild)
        {
            setEqual((TEqual) newChild);
            return;
        }

        if(this._p_ == oldChild)
        {
            setP((PP) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
