/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AEtO extends PO
{
    private PO _o_;
    private TEt _et_;
    private PE _e_;

    public AEtO()
    {
        // Constructor
    }

    public AEtO(
        @SuppressWarnings("hiding") PO _o_,
        @SuppressWarnings("hiding") TEt _et_,
        @SuppressWarnings("hiding") PE _e_)
    {
        // Constructor
        setO(_o_);

        setEt(_et_);

        setE(_e_);

    }

    @Override
    public Object clone()
    {
        return new AEtO(
            cloneNode(this._o_),
            cloneNode(this._et_),
            cloneNode(this._e_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEtO(this);
    }

    public PO getO()
    {
        return this._o_;
    }

    public void setO(PO node)
    {
        if(this._o_ != null)
        {
            this._o_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._o_ = node;
    }

    public TEt getEt()
    {
        return this._et_;
    }

    public void setEt(TEt node)
    {
        if(this._et_ != null)
        {
            this._et_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._et_ = node;
    }

    public PE getE()
    {
        return this._e_;
    }

    public void setE(PE node)
    {
        if(this._e_ != null)
        {
            this._e_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._o_)
            + toString(this._et_)
            + toString(this._e_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._o_ == child)
        {
            this._o_ = null;
            return;
        }

        if(this._et_ == child)
        {
            this._et_ = null;
            return;
        }

        if(this._e_ == child)
        {
            this._e_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._o_ == oldChild)
        {
            setO((PO) newChild);
            return;
        }

        if(this._et_ == oldChild)
        {
            setEt((TEt) newChild);
            return;
        }

        if(this._e_ == oldChild)
        {
            setE((PE) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
