/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ALessE extends PE
{
    private PE _e_;
    private TLess _less_;
    private PP _p_;

    public ALessE()
    {
        // Constructor
    }

    public ALessE(
        @SuppressWarnings("hiding") PE _e_,
        @SuppressWarnings("hiding") TLess _less_,
        @SuppressWarnings("hiding") PP _p_)
    {
        // Constructor
        setE(_e_);

        setLess(_less_);

        setP(_p_);

    }

    @Override
    public Object clone()
    {
        return new ALessE(
            cloneNode(this._e_),
            cloneNode(this._less_),
            cloneNode(this._p_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALessE(this);
    }

    public PE getE()
    {
        return this._e_;
    }

    public void setE(PE node)
    {
        if(this._e_ != null)
        {
            this._e_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e_ = node;
    }

    public TLess getLess()
    {
        return this._less_;
    }

    public void setLess(TLess node)
    {
        if(this._less_ != null)
        {
            this._less_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._less_ = node;
    }

    public PP getP()
    {
        return this._p_;
    }

    public void setP(PP node)
    {
        if(this._p_ != null)
        {
            this._p_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._p_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._e_)
            + toString(this._less_)
            + toString(this._p_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._e_ == child)
        {
            this._e_ = null;
            return;
        }

        if(this._less_ == child)
        {
            this._less_ = null;
            return;
        }

        if(this._p_ == child)
        {
            this._p_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._e_ == oldChild)
        {
            setE((PE) newChild);
            return;
        }

        if(this._less_ == oldChild)
        {
            setLess((TLess) newChild);
            return;
        }

        if(this._p_ == oldChild)
        {
            setP((PP) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
