/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AListedinstrInstrbloc extends PInstrbloc
{
    private TLAccolade _lAccolade_;
    private PListeinstr _listeinstr_;
    private TRAccolade _rAccolade_;

    public AListedinstrInstrbloc()
    {
        // Constructor
    }

    public AListedinstrInstrbloc(
        @SuppressWarnings("hiding") TLAccolade _lAccolade_,
        @SuppressWarnings("hiding") PListeinstr _listeinstr_,
        @SuppressWarnings("hiding") TRAccolade _rAccolade_)
    {
        // Constructor
        setLAccolade(_lAccolade_);

        setListeinstr(_listeinstr_);

        setRAccolade(_rAccolade_);

    }

    @Override
    public Object clone()
    {
        return new AListedinstrInstrbloc(
            cloneNode(this._lAccolade_),
            cloneNode(this._listeinstr_),
            cloneNode(this._rAccolade_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListedinstrInstrbloc(this);
    }

    public TLAccolade getLAccolade()
    {
        return this._lAccolade_;
    }

    public void setLAccolade(TLAccolade node)
    {
        if(this._lAccolade_ != null)
        {
            this._lAccolade_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lAccolade_ = node;
    }

    public PListeinstr getListeinstr()
    {
        return this._listeinstr_;
    }

    public void setListeinstr(PListeinstr node)
    {
        if(this._listeinstr_ != null)
        {
            this._listeinstr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listeinstr_ = node;
    }

    public TRAccolade getRAccolade()
    {
        return this._rAccolade_;
    }

    public void setRAccolade(TRAccolade node)
    {
        if(this._rAccolade_ != null)
        {
            this._rAccolade_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rAccolade_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lAccolade_)
            + toString(this._listeinstr_)
            + toString(this._rAccolade_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lAccolade_ == child)
        {
            this._lAccolade_ = null;
            return;
        }

        if(this._listeinstr_ == child)
        {
            this._listeinstr_ = null;
            return;
        }

        if(this._rAccolade_ == child)
        {
            this._rAccolade_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lAccolade_ == oldChild)
        {
            setLAccolade((TLAccolade) newChild);
            return;
        }

        if(this._listeinstr_ == oldChild)
        {
            setListeinstr((PListeinstr) newChild);
            return;
        }

        if(this._rAccolade_ == oldChild)
        {
            setRAccolade((TRAccolade) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
