/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ANM extends PM
{
    private PN _n_;

    public ANM()
    {
        // Constructor
    }

    public ANM(
        @SuppressWarnings("hiding") PN _n_)
    {
        // Constructor
        setN(_n_);

    }

    @Override
    public Object clone()
    {
        return new ANM(
            cloneNode(this._n_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANM(this);
    }

    public PN getN()
    {
        return this._n_;
    }

    public void setN(PN node)
    {
        if(this._n_ != null)
        {
            this._n_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._n_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._n_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._n_ == child)
        {
            this._n_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._n_ == oldChild)
        {
            setN((PN) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
