/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AOS extends PS
{
    private PO _o_;

    public AOS()
    {
        // Constructor
    }

    public AOS(
        @SuppressWarnings("hiding") PO _o_)
    {
        // Constructor
        setO(_o_);

    }

    @Override
    public Object clone()
    {
        return new AOS(
            cloneNode(this._o_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOS(this);
    }

    public PO getO()
    {
        return this._o_;
    }

    public void setO(PO node)
    {
        if(this._o_ != null)
        {
            this._o_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._o_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._o_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._o_ == child)
        {
            this._o_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._o_ == oldChild)
        {
            setO((PO) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
