/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class APE extends PE
{
    private PP _p_;

    public APE()
    {
        // Constructor
    }

    public APE(
        @SuppressWarnings("hiding") PP _p_)
    {
        // Constructor
        setP(_p_);

    }

    @Override
    public Object clone()
    {
        return new APE(
            cloneNode(this._p_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPE(this);
    }

    public PP getP()
    {
        return this._p_;
    }

    public void setP(PP node)
    {
        if(this._p_ != null)
        {
            this._p_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._p_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._p_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._p_ == child)
        {
            this._p_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._p_ == oldChild)
        {
            setP((PP) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
