/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class ASinonInstr extends PInstr
{
    private TSi _si_;
    private PExp _exp_;
    private TAlors _alors_;
    private PInstrbloc _thenbranch_;
    private TSinon _sinon_;
    private PInstrbloc _elsebranch_;

    public ASinonInstr()
    {
        // Constructor
    }

    public ASinonInstr(
        @SuppressWarnings("hiding") TSi _si_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TAlors _alors_,
        @SuppressWarnings("hiding") PInstrbloc _thenbranch_,
        @SuppressWarnings("hiding") TSinon _sinon_,
        @SuppressWarnings("hiding") PInstrbloc _elsebranch_)
    {
        // Constructor
        setSi(_si_);

        setExp(_exp_);

        setAlors(_alors_);

        setThenbranch(_thenbranch_);

        setSinon(_sinon_);

        setElsebranch(_elsebranch_);

    }

    @Override
    public Object clone()
    {
        return new ASinonInstr(
            cloneNode(this._si_),
            cloneNode(this._exp_),
            cloneNode(this._alors_),
            cloneNode(this._thenbranch_),
            cloneNode(this._sinon_),
            cloneNode(this._elsebranch_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASinonInstr(this);
    }

    public TSi getSi()
    {
        return this._si_;
    }

    public void setSi(TSi node)
    {
        if(this._si_ != null)
        {
            this._si_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._si_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TAlors getAlors()
    {
        return this._alors_;
    }

    public void setAlors(TAlors node)
    {
        if(this._alors_ != null)
        {
            this._alors_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._alors_ = node;
    }

    public PInstrbloc getThenbranch()
    {
        return this._thenbranch_;
    }

    public void setThenbranch(PInstrbloc node)
    {
        if(this._thenbranch_ != null)
        {
            this._thenbranch_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._thenbranch_ = node;
    }

    public TSinon getSinon()
    {
        return this._sinon_;
    }

    public void setSinon(TSinon node)
    {
        if(this._sinon_ != null)
        {
            this._sinon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sinon_ = node;
    }

    public PInstrbloc getElsebranch()
    {
        return this._elsebranch_;
    }

    public void setElsebranch(PInstrbloc node)
    {
        if(this._elsebranch_ != null)
        {
            this._elsebranch_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elsebranch_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._si_)
            + toString(this._exp_)
            + toString(this._alors_)
            + toString(this._thenbranch_)
            + toString(this._sinon_)
            + toString(this._elsebranch_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._si_ == child)
        {
            this._si_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._alors_ == child)
        {
            this._alors_ = null;
            return;
        }

        if(this._thenbranch_ == child)
        {
            this._thenbranch_ = null;
            return;
        }

        if(this._sinon_ == child)
        {
            this._sinon_ = null;
            return;
        }

        if(this._elsebranch_ == child)
        {
            this._elsebranch_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._si_ == oldChild)
        {
            setSi((TSi) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._alors_ == oldChild)
        {
            setAlors((TAlors) newChild);
            return;
        }

        if(this._thenbranch_ == oldChild)
        {
            setThenbranch((PInstrbloc) newChild);
            return;
        }

        if(this._sinon_ == oldChild)
        {
            setSinon((TSinon) newChild);
            return;
        }

        if(this._elsebranch_ == oldChild)
        {
            setElsebranch((PInstrbloc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
