/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class AVarindexeeVar extends PVar
{
    private TIdentif _identif_;
    private TBrackopen _brackopen_;
    private PS _s_;
    private TBrackclose _brackclose_;

    public AVarindexeeVar()
    {
        // Constructor
    }

    public AVarindexeeVar(
        @SuppressWarnings("hiding") TIdentif _identif_,
        @SuppressWarnings("hiding") TBrackopen _brackopen_,
        @SuppressWarnings("hiding") PS _s_,
        @SuppressWarnings("hiding") TBrackclose _brackclose_)
    {
        // Constructor
        setIdentif(_identif_);

        setBrackopen(_brackopen_);

        setS(_s_);

        setBrackclose(_brackclose_);

    }

    @Override
    public Object clone()
    {
        return new AVarindexeeVar(
            cloneNode(this._identif_),
            cloneNode(this._brackopen_),
            cloneNode(this._s_),
            cloneNode(this._brackclose_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarindexeeVar(this);
    }

    public TIdentif getIdentif()
    {
        return this._identif_;
    }

    public void setIdentif(TIdentif node)
    {
        if(this._identif_ != null)
        {
            this._identif_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identif_ = node;
    }

    public TBrackopen getBrackopen()
    {
        return this._brackopen_;
    }

    public void setBrackopen(TBrackopen node)
    {
        if(this._brackopen_ != null)
        {
            this._brackopen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._brackopen_ = node;
    }

    public PS getS()
    {
        return this._s_;
    }

    public void setS(PS node)
    {
        if(this._s_ != null)
        {
            this._s_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._s_ = node;
    }

    public TBrackclose getBrackclose()
    {
        return this._brackclose_;
    }

    public void setBrackclose(TBrackclose node)
    {
        if(this._brackclose_ != null)
        {
            this._brackclose_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._brackclose_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identif_)
            + toString(this._brackopen_)
            + toString(this._s_)
            + toString(this._brackclose_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identif_ == child)
        {
            this._identif_ = null;
            return;
        }

        if(this._brackopen_ == child)
        {
            this._brackopen_ = null;
            return;
        }

        if(this._s_ == child)
        {
            this._s_ = null;
            return;
        }

        if(this._brackclose_ == child)
        {
            this._brackclose_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identif_ == oldChild)
        {
            setIdentif((TIdentif) newChild);
            return;
        }

        if(this._brackopen_ == oldChild)
        {
            setBrackopen((TBrackopen) newChild);
            return;
        }

        if(this._s_ == oldChild)
        {
            setS((PS) newChild);
            return;
        }

        if(this._brackclose_ == oldChild)
        {
            setBrackclose((TBrackclose) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
