/* This file was generated by SableCC (http://www.sablecc.org/). */

package postfix.node;

import postfix.analysis.*;

@SuppressWarnings("nls")
public final class TSautDeLigne extends Token
{
    public TSautDeLigne()
    {
        super.setText("\\n");
    }

    public TSautDeLigne(int line, int pos)
    {
        super.setText("\\n");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSautDeLigne(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSautDeLigne(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSautDeLigne text.");
    }
}
